package com.idforideas.wikideas.model;

import com.idforideas.wikideas.dto.validator.IValidatorArticle;
import com.idforideas.wikideas.dto.validator.IValidatorTheme;
import com.idforideas.wikideas.utils.DTOValidator;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ThemeEnum {
    ACTUALIDAD("ACTUALIDAD", 1L),
    AGRICULTURA("AGRICULTURA", 2L),
    ANTROPOLOGIA("ANTROPOLOGIA", 3L),
    ARQUEOLOGIA("ARQUEOLOGIA", 4L),
    ARQUITECTURA("ARQUITECTURA", 5L),
    ARTE("ARTE", 6L),
    CINE("CINE", 7L),
    DANZA("DANZA", 8L),
    MUSICA("MUSICA", 9L),
    ARTESANIA("ARTESANIA", 10L),
    ASTRONOMIA("ASTRONOMIA", 11L),
    AERONAUTICA("AERONAUTICA", 12L),
    CIENCIA_FICCION("CIENCIA FICCION", 13L),
    CIENCIAS("CIENCIAS", 14L),
    BIOLOGIA("BIOLOGIA", 15L),
    FISICA("FISICA", 16L),
    GEOLOGIA("GEOLOGIA", 17L),
    MATEMATICAS("MATEMATICAS", 18L),
    QUIMICA("QUIMICA", 19L),
    COMUNICACION("COMUNICACION", 20L),
    CULTURA("CULTURA", 21L),
    DEPORTES("DEPORTES", 22L),
    FUTBOL("FUTBOL", 23L),
    DERECHO("DERECHO", 24L),
    DISEÑO("DISEÑO", 25L),
    ECONOMIA("ECONOMIA", 26L),
    EMPRESA("EMPRESA", 27L),
    EDUCACION("EDUCACION", 28L),
    FILOSOFIA("FILOSOFIA", 29L),
    FOTOGRAFIA("FOTOGRAFIA", 30L),
    GASTRONOMIA("GASTRONOMIA", 31L),
    INGENIERIA("INGENIERIA", 32L),
    GEOGRAFIA("GEOGRAFIA", 33L),
    HISTORIA("HISTORIA", 34L),
    HISTORIETA("HISTORIETA", 35L),
    INFORMATICA("INFORMATICA", 36L),
    JUEGOS("JUEGOS", 37L),
    IDIOMAS("IDIOMAS", 38L),
    MEDICINA("MEDICINA", 39L),
    MEDIO_AMBIENTE("MEDIO AMBIENTE", 40L),
    MECANICA_MOTORES("MECANICA MOTORES", 41L),
    PAISES("PAISES", 42L),
    POLITICA("POLITICA", 43L),
    PSICOLOGIA("PSICOLOGIA", 44L),
    RELIGION("RELIGION", 45L),
    SOCIOLOGIA("SOCIOLOGIA", 46L),
    TECNOLOGIA("TECNOLOGIA", 47L),
    SERIES("SERIES", 48L),
    PELICULAS("PELICULAS", 49L),
    PROGRAMAS_TV("PROGRAMAS TV", 50L);
    private String theme;
    private Long id;

}
